server:
  port: 4005 # Gateway listens on port 4005

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
            - "http://localhost:3000"
            allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowed-headers:
            - "*"

      routes:
      - id: job-application-service-route
        uri: http://job-application-service:4000
        predicates:
          - Path=/api/job-applications/**
        filters:
          - StripPrefix=1

      - id: api-docs-job-application-route
        uri: http://job-application:4000
        predicates:
          - Path=/api-docs/job-applications/**
        filters:
          - RewritePath=/api-docs/job-applications,/v3/api-docs